export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_MOVIES_SUCCESS="GET_MOVIES_SUCCESS"
export const CREATE_MOVIE_SUCCESS="CREATE_MOVIE_SUCCESS"
export const UPDATE_MOVIE_SUCCESS="UPDATE_MOVIE_SUCCESS"

export const ADD_TO_FAVORITE="ADD_TO_FAVORITE"
export const REMOVE_FROM_FAVORITE="REMOVE_FROM_FAVORITE"
